### ISSUE TITLE
Type Issue with return type of `parse` method

### ISSUE THREAD

**Issue by tumainimosha** [mCzolko/nest-csv-parser#46]
<img width="1023" alt="Screenshot 2020-06-24 at 21 09 40" src="https://user-images.githubusercontent.com/7481490/85615231-9752eb00-b664-11ea-8036-bd9dbf0a3618.png">

I have followed example code on Readme of this project, but typescript is complaining on return type for parse method not matching array of entities. (see screenshot above)

**Comment by mCzolko** [comment]
I might have it wrong in the docs, the second parameter of the parse() method might be an instance of the entity, not a type...

**Comment by jimmyjamieson** [comment]
import { ParsedData } from 'nest-csv-parser';

const entities: ParsedData<any> = await this.csvParser.parse(...)
