### ISSUE TITLE
v2 has no exported member 'CsvModule`

### ISSUE THREAD

**Issue by douglance** [mCzolko/nest-csv-parser#55]
I upgraded the package and received this error:

```
TSError: ⨯ Unable to compile TypeScript:
src/modules/elements/element.module.ts:4:10 - error TS2305: Module '"../../../../../node_modules/nest-csv-parser"' has no exported member 'CsvModule'.

4 import { CsvModule } from 'nest-csv-parser';
           ~~~~~~~~~
```

**Comment by dr5hn** [comment]
@mCzolko I think release is missing main code.

<img width="284" alt="Screenshot 2020-07-21 at 8 30 55 PM" src="https://user-images.githubusercontent.com/6929121/88071156-1c142480-cb91-11ea-89b2-29f1e3570bce.png">

There is no `dist` folder which you've specified in index.d.ts

**Comment by mCzolko** [comment]
I'm so sorry, this was my mistake. Please update dependency to latest version `2.0.4`
